name: geocode-csv 
version: 1.0
summary: GEOCODE CSV
description: |
  GEOCODE CSV fornece serviço de geolocalização a listas de endereços.

grade: devel
confinement: devmode

apps:
  geocode-csv:
    command: geocode

parts:
  geocode-csv:
    plugin: python3
    source: https://github.com/pvmm/my-pyqt-samples
    source-type: git
    stage-packages:
      - python3-pyqt5
      - libc-bin
      - locales
